service: swing-notes-api-aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  signup:
    handler: src/functions/signup/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: src/functions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
  getNotes:
    handler: src/functions/getNotes/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: GET
  createNote:
    handler: src/functions/createNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: POST
  updateNote:
    handler: src/functions/updateNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: PUT
  deleteNote:
    handler: src/functions/deleteNote/index.handler
    events:
      - httpApi:
          path: '/api/notes'
          method: DELETE

resources:
  Resources:
    swingNotes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: swingNotes
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
          - AttributeName: entityType
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: GSI
            KeySchema:
              - AttributeName: entityType
                KeyType: HASH
              - AttributeName: sortKey
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
